### ISSUE TITLE
pay_dun00.rsw not found

### ISSUE THREAD

**Issue by shujaatak** [vE5li/korangar#1]
It would be nice if you please add pay_dun00.rsw to the repository.
It would be awesome if you please include data files.

**Comment by vE5li** [comment]
Hello :) 

I didn't add pay_dun00.rsw for copyright reasons. I would be happy to send you a Zip file containing the necessary data to run Korangar if you want :) 

Dec 29, 2021, 07:31 by ***@***.***:

**Comment by shujaatak** [comment]
That would be so nice if you send me that data to this email:
shujaat.eager
@
gmail.com
