### ISSUE TITLE
Map / Entity colors are much less vibrant in Korangar than in official client

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#135]
In Lighthalzen Town:

Korangar (At Noon):
![Screenshot_20241103_111850](https://github.com/user-attachments/assets/21f5a2f4-59c8-462d-b186-62776294f3da)

Official Client:
![Screenshot_20241103_111858](https://github.com/user-attachments/assets/df82aa5b-1280-40b5-918b-fc660534f6f8)

**Comment by hasenbanck** [comment]
@eleriaqueen Can you please test  #183 and judge if the classic lightning mode is closer to what you would expect?

**Comment by eleriaqueen** [comment]
I've tested classic lighting mode and yes it's quite a bit closer to the "official client look".
![Screenshot_20241208_103008](https://github.com/user-attachments/assets/6809088c-d393-47f5-a4d8-89d30368d415)

**Comment by hasenbanck** [comment]
In term of vibrancy we should be more ot less the same now. Can I close this tickert for now?

**Comment by eleriaqueen** [comment]
Yes.
