### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Jlabarca** [vE5li/korangar#2]
The project looks great!

I know it's in progress but could you guys share info about how to run it?

Thanks

**Comment by vE5li** [comment]
Thanks you! 

Currently it's a bit difficult to run the client but when i get back home later this week i will push some changes (including instructions in the README) that will make it a lot easier :)

**Comment by vE5li** [comment]
I just pushed some changes that should hopefully make the setup process relatively easy. If you have any issues you can post them to the Discord server I linked in the README or create another issue. Enjoy :)
