### ISSUE TITLE
Fix logging out to character select

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#26]
Korangar currently does not log out to character select screen when clicking on the menu option.

Logout event occurs:

![Screenshot_2023-07-20_23-57-43](https://github.com/vE5li/korangar/assets/4411178/70841858-2a23-40b8-98ba-4b686248de0d)

But according to the Packet Debugger no packet is sent.

**Comment by vE5li** [comment]
That is correct. When I added the button I tried to find the correct packet to send for logging out but I couldn't find it

**Comment by eleriaqueen** [comment]
Is it possible official client uses packet CZ_RESTART for logging off ?
(Source: rAthena)
```
/// Response to the death/system menu (CZ_RESTART).
/// 00b2 <type>.B
/// type:
///     0 = restart (respawn)
///     1 = char-select (disconnect)
```

**Comment by vE5li** [comment]
Fixed as of https://github.com/vE5li/korangar/commit/a1f8b8ea3a34f5e7fe6e5894072246e13247cbef :+1:
