### ISSUE TITLE
Improve text legibility

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#27]
At the moment most in-game text looks "soft". Default font size also makes some of it barely legible.
The most egregious example of hard to read text is chat-box text, in particular when a message is in colour.

**Comment by hasenbanck** [comment]
@eleriaqueen Can you please re-test how text legibility is for you? We updated the rendering of the UI and fonts.

For 4k displays I suggest following configuration:

1. Interface Scaling: 1.5
2. Activate the High Quality UI graphics option

You might need to re-size the windows using rightclick + shift.

**Comment by eleriaqueen** [comment]
Thanks for pinging me about this I forgot I even opened this issue.
It seems I need around 1.6 x scale factor for the UI to be comfortable to read. 
New font "engine" is very good and legibility has indeed been addressed.
![Screenshot_20241130_034924](https://github.com/user-attachments/assets/8b63e0bd-b658-4c20-a79a-7e3b8a4c2248)

**Comment by hasenbanck** [comment]
Thank you for the feedback. I will close this ticket then for now. The hover text issue is tracked in #41  and will be fixed, once I ported the new font engine to be used in hover text rendering.
