### ISSUE TITLE
ESC menu can be brought up at any point during login

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#32]
ESC menu can be invoked at any time during login currently, this can cause issues (Logout function used this early crashes Korangar... etc)

![Screenshot_2023-07-24_01-06-06](https://github.com/vE5li/korangar/assets/4411178/ae6c0a50-6b15-4236-9ada-bb0645accd4f)

**Comment by vE5li** [comment]
Fixed as of https://github.com/vE5li/korangar/commit/88fac8fe64dfa252ccab7ef541624dd36a559d28
