### ISSUE TITLE
Moving just one block quickly resets the walking animation

### ISSUE THREAD

**Issue by gustavobca** [vE5li/korangar#35]
https://gyazo.com/c6057523bcc8ba850e7b7799946d8d6c

**Comment by aleDsz** [comment]
If you use `@speed 0`, it jumps to the block, instead of executing the animation more fast until reaches the position you clicked to.

**Comment by gustavobca** [comment]
The animation should not reset by doing this

**Comment by eleriaqueen** [comment]
Official client has a walkDelay
![Screenshot_2023-07-25_08-38-02](https://github.com/vE5li/korangar/assets/4411178/f0ef6813-822d-47b9-98b0-86ffc3815933)

**Comment by eleriaqueen** [comment]
I managed to successfully emulate this delay: 

I declared a move_start_time: as global variable
```
    let mut move_start_time = Instant::now();
```

then a 600 ms check and I reset move_start_time player moved
```
                        UserEvent::RequestPlayerMove(destination) => {
                            if !entities.is_empty() && (move_start_time.elapsed().as_millis() > 600) {
                                networking_system.request_player_move(destination)
                                move_start_time = Instant::now();
                            }
                        }
```

**Comment by vE5li** [comment]
I tested it just now and I think it's fine, but I would love some more input on this from other people. I myself am not 100% sure that a walk delay is the right solution in fear that the player might feel sluggish and unresponsive. So it would be great everyone could test #36 and give some feedback

**Comment by eleriaqueen** [comment]
I think code for a walk delay (not necessarily the way I did it) should be added because it's official behavior and people are used to it. Duration of this delay could be set to 0 and people are free to add the delay they feel is acceptable (?)

**Comment by vE5li** [comment]
> I think there is value in code implementing a walk delay (not necessarily the way I did it) because it's official behavior and people are used to it.
I don't disagree with this, and if the general response on #36 is good I am all for merging it. Like I said, just want some more feedback from other people

**Comment by eleriaqueen** [comment]
There may be a fix to prevent characters stuttering when mashing left click to move and animation resetting when changing direction, a fix that much less impacts the responsiveness of the game.
The idea is not to restart animation when character is already walking.

I committed the change to a branch in my fork but didn't do a PR because I felt opening a second PR for the same issue would be bad, but at the same time it doesn't necessarily supersedes the PR I did earlier...
[No Walk Animation Reset When Spamming Right-Click](https://github.com/vE5li/korangar/compare/main...eleriaqueen:korangar:no-walk-anim-reset-on-spam-click )

**Comment by gustavobca** [comment]
> There may be a fix to prevent characters stuttering when mashing left click to move and animation resetting when changing direction, a fix that much less impacts the responsiveness of the game. The idea is not to restart animation when character is already walking.
> 
> I committed the change to a branch in my fork but didn't do a PR because I felt opening a second PR for the same issue would be bad, but at the same time it doesn't necessarily supersedes the PR I did earlier... [No Walk Animation Reset When Spamming Left-Click](https://github.com/vE5li/korangar/compare/main...eleriaqueen:korangar:no-walk-anim-reset-on-spam-click)

This is what I talking about, can you send a gif of how it turned out?

**Comment by eleriaqueen** [comment]
Here with the fix in place I mash left-click.
https://github.com/vE5li/korangar/assets/4411178/4146d990-2bad-4eab-9ad4-7a7abbf23330

**Comment by gustavobca** [comment]
> @gustavobca Here with the fix that prevents animation from resetting in place I mash left-click.
> 
> ![stutter-step-fix-v2](https://user-images.githubusercontent.com/4411178/256015975-7ff4561c-7421-43a5-82e2-00bb74e06aee.gif)
> 
> Fix from PR more or less looks the same except it completely prevents walking until 300 ms have passed which means a loss of responsiveness.

It looks good, what can be done also not reset if the time from one walk to the other is less than the player's speed converted to ms (must have the formula in the same file)

**Comment by vE5li** [comment]
I implemented @eleriaqueen's approach of not resetting the animation if it's already playing and personally I think it works really well. So I'm closing this issue as of https://github.com/vE5li/korangar/commit/ddaefc224ffc7e368a99b96e6f16e460449377e3
