### ISSUE TITLE
There's no indicator highlighting cell under cursor

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#37]
Official behavior is this:

![Screenshot_2023-07-25_12-47-43](https://github.com/vE5li/korangar/assets/4411178/068f73b5-3b72-4609-810b-9b8aa1a460ab)

**Comment by vE5li** [comment]
Implemented in https://github.com/vE5li/korangar/commit/6fe6b492ca611fc84ca9e3c3c5068c7f88395249
