### ISSUE TITLE
With left-mousebutton kept down the player character should keep walking

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#39]
Currently keeping left-click down does nothing more than the initial move, character stops at initial destination without changing its course.
On official client keeping left-click down makes the character move until an obstacle is in the way, or until the user lets go of the button.

Short gif of me clicking once and not letting go (official client):
![keep-walking](https://github.com/vE5li/korangar/assets/4411178/e21f90ad-4b48-4ef7-ac44-7eb1cb34bfd3)

**Comment by vE5li** [comment]
Fixed as of #40
