### ISSUE TITLE
Logging out then back in sometimes hard crashes the client

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#42]
[logging-out-then-in-crash.webm](https://github.com/vE5li/korangar/assets/4411178/ff68c31a-96be-4bac-ae1a-39b6047ed744)

Also, when logging in, often the player characters appears on the right map server wise, right coords too, but client doesn't "see" any NPC. Warping to the same map or another fixes it.

**Comment by vE5li** [comment]
While I have seen this happen too, I can not reproduce it now. Given that the behavior of the client should be the same every time you re-log and it works most of the time, I would suspect that the error is maybe on rAthena's side. Nevertheless I will leave this issue open for now to collect information.

**Comment by eleriaqueen** [comment]
This seems to only happen on my test server now which is strange, aside from removing PIN entry and using different packetver than the standard rAthena one I really haven't much if anything at all...

**Comment by eleriaqueen** [comment]
Okay finally getting somewhere, I checked rathena-map server and there's an error message everytime Korangar crashes when doing the login/out cycle.

```
clif_parse: Disconnecting session #8 with unknown connect packet 0x0436(length:25)
```

**Comment by vE5li** [comment]
I have not seen this happen in a very long time, so I will assume whatever was causing this has been fixed
