### ISSUE TITLE
Integrated GPU Intel 770 supports PushConstants of size 128 max

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#47]
I usually use my Nvidia GPU which runs Korangar no problem, but decided for tesing purposes to try using my integrated GPU which is `Intel(R) UHD Graphics 770 (ADL-S GT1)`  and crashed with an error when dealing with the "ground indicator" shader: 
```
MaxPushConstantsSizeExceeded { provided: 140, max_supported: 128 }
```

According to the vulkan spec 128 is the very minimum a card can have as constants "buffer".

**Comment by vE5li** [comment]
Fixed as of https://github.com/vE5li/korangar/commit/6e7205b34f2dbea01ddec34fd828a893d3f4fcc1
