### ISSUE TITLE
Add in-game setting for shadow detail

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#66]
Currently shadow detail is hard-coded to 8192 in `src/main.rs` which isn't ideal.
I usually like to set it to a much lower value like 2048 just to get much better performance and to tax my GPU less when doing some debugging.
An in-game setting would be pretty neat.

**Comment by vE5li** [comment]
The main reason I didn't do that yet is because there is no UI element to select from a number of options. I have started adding one as part of the UI improvements, so I will get to work on this soon :+1:

**Comment by vE5li** [comment]
Solved as of https://github.com/vE5li/korangar/commit/f3f30b24f5a59f3146b47c6cb69d6ac546b6e1bf
